<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a828c635-ae37-4254-aa3d-12f0bb2c338f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Identity\RentIt.Modules.Identity.Api\RentIt.Modules.Identity.Api.csproj" />
    <ProjectReference Include="..\..\Modules\Analytics\RentIt.Modules.Analytics.Api\RentIt.Modules.Analytics.Api.csproj" />
    <ProjectReference Include="..\..\Modules\Bookings\RentIt.Modules.Bookings.Api\RentIt.Modules.Bookings.Api.csproj" />
    <ProjectReference Include="..\..\Modules\Messaging\RentIt.Modules.Messaging.Api\RentIt.Modules.Messaging.Api.csproj" />
    <ProjectReference Include="..\..\Modules\Payments\RentIt.Modules.Payments.Api\RentIt.Modules.Payments.Api.csproj" />
    <ProjectReference Include="..\..\Modules\Properties\RentIt.Modules.Properties.Api\RentIt.Modules.Properties.Api.csproj" />
    <ProjectReference Include="..\..\Modules\Reviews\RentIt.Modules.Reviews.Api\RentIt.Modules.Reviews.Api.csproj" />
    <ProjectReference Include="..\..\Modules\Verification\RentIt.Modules.Verification.Api\RentIt.Modules.Verification.Api.csproj" />
    <ProjectReference Include="..\..\Shared\RentIt.Shared.Infrastructure\RentIt.Shared.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Analytics\RentIt.Modules.Analytics.Application\RentIt.Modules.Analytics.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Analytics\RentIt.Modules.Analytics.Infrastructure\RentIt.Modules.Analytics.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <ProjectReference Include="..\..\Modules\Payments\RentIt.Modules.Payments.Api\RentIt.Modules.Payments.Api.csproj" />
    <ProjectReference Include="..\..\Modules\Payments\RentIt.Modules.Payments.Application\RentIt.Modules.Payments.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Payments\RentIt.Modules.Payments.Infrastructure\RentIt.Modules.Payments.Infrastructure.csproj" />
  </ItemGroup>

</Project>
