<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <NoWarn>$(NoWarn);IDX00001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <!-- Common NuGet packages for all projects -->
  </ItemGroup>

</Project>
