<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f36b6832-c4a7-45e3-8e2d-8715404c5abf</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Facebook" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.MicrosoftAccount" />
    <PackageReference Include="Google.Apis.Auth.AspNetCore3" />
    <PackageReference Include="Yarp.ReverseProxy" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\RentIt.Shared.Contracts\RentIt.Shared.Contracts.csproj" />
    <ProjectReference Include="..\..\Shared\RentIt.Shared.DTOs\RentIt.Shared.DTOs.csproj" />
  </ItemGroup>

</Project>
