<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\RentIt.Modules.Identity.Application\RentIt.Modules.Identity.Application.csproj" />
    <ProjectReference Include="..\RentIt.Modules.Identity.Infrastructure\RentIt.Modules.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Shared\RentIt.Shared.Contracts\RentIt.Shared.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b6cec765-e63f-4726-9c78-b87c6acebfa9</UserSecretsId>
  </PropertyGroup>

</Project>
