<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>72fa4ec6-edfc-4f3f-823d-c5fd19bf9fc0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RentIt.Modules.Properties.Infrastructure\RentIt.Modules.Properties.Infrastructure.csproj" />
  </ItemGroup>

</Project>
