<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Moq" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Analytics\RentIt.Modules.Analytics.Api\RentIt.Modules.Analytics.Api.csproj" />
    <ProjectReference Include="..\..\Modules\Analytics\RentIt.Modules.Analytics.Application\RentIt.Modules.Analytics.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Analytics\RentIt.Modules.Analytics.Domain\RentIt.Modules.Analytics.Domain.csproj" />
    <ProjectReference Include="..\..\Shared\RentIt.Shared.Abstractions\RentIt.Shared.Abstractions.csproj" />
    <ProjectReference Include="..\..\Shared\RentIt.Shared.Contracts\RentIt.Shared.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
