<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CloudinaryDotNet" />
    <PackageReference Include="Fluid.Core" />
    <PackageReference Include="MailKit" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Email\Templates\*.liquid" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Analytics\RentIt.Modules.Analytics.Domain\RentIt.Modules.Analytics.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Bookings\RentIt.Modules.Bookings.Domain\RentIt.Modules.Bookings.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Identity\RentIt.Modules.Identity.Domain\RentIt.Modules.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Messaging\RentIt.Modules.Messaging.Domain\RentIt.Modules.Messaging.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Payments\RentIt.Modules.Payments.Domain\RentIt.Modules.Payments.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Properties\RentIt.Modules.Properties.Domain\RentIt.Modules.Properties.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Reviews\RentIt.Modules.Reviews.Domain\RentIt.Modules.Reviews.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Verification\RentIt.Modules.Verification.Domain\RentIt.Modules.Verification.Domain.csproj" />
    <ProjectReference Include="..\RentIt.Shared.Abstractions\RentIt.Shared.Abstractions.csproj" />
  </ItemGroup>

</Project>
